# string type
[[schema]]
topics = [
    "ems/site/site_1/root/allowed_max_p/data",

]
qos = 0

[schema.payload]
type = "object"

[schema.payload.properties]
ts = { type = "timestamp", start_time = 2025-10-01T00:00:00.888000999, interval = "1ms", tick = 4 }
value = { type = "option", value = { type = "string", length = { range = { min = 10, max = 100 } } } }

# number type

[[schema]]
topics = [
    "ems/site/site_1/meter/meter_1/hz/data",

]
qos = 0

[schema.payload]
type = "object"

[schema.payload.properties]
ts = { type = "timestamp", start_time = 2025-10-01T00:00:00.888, interval = "1ms", tick = 200 }
value = { type = "number", range = { min = 1, max = 1000 } }

# float type

[[schema]]
topics = [
    "ems/site/site_1/unit/unit_1/root/run_mode/data",
]
qos = 0

[schema.payload]
type = "object"

[schema.payload.properties]
ts = { type = "timestamp", start_time = 2025-10-01T00:00:00.888, interval = "1ms", tick = 200 }
value = { type = "float", range = { min = 0.1, max = 0.9 } }

# bool type

[[schema]]
topics = [
    "ems/site/site_1/unit/unit_1/pcs/pcs_1/status/data",
]
qos = 0

[schema.payload]
type = "object"

[schema.payload.properties]
ts = { type = "timestamp", start_time = 2025-10-01T00:00:00.888, interval = "1ms", tick = 200 }
value = { type = "number", range = { min = 0, max = 1 } }

